language: node_js

sudo: false

node_js:
    - "8.0"

cache:
    yarn: true


install:
    - yarn --pure-lockfile

script:
    - yarn run build

deploy:
    provider: pages
    local_dir: ./dist
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master


notifications:
    email: false